In [1]:
import tensorflow as tf

2026-01-29 00:59:02.681714: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2026-01-29 00:59:02.692010: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-01-29 00:59:03.104137: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-01-29 00:59:04.815816: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To tur

In [2]:
mnist = tf.keras.datasets.mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [3]:
X_train.shape

(60000, 28, 28)

In [4]:
 X_test.shape

(10000, 28, 28)

In [5]:
y_train.shape

(60000,)

In [6]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

DATA PREPROCESSING

Unlike models like decision trees or random forests Neural nets are scale sensitive, thus its hard for them to handle values on random scale, therefore we normalize the data

In [7]:
X_train, X_test = X_train/255.0, X_test/255.0

In [8]:
X_train[0]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [9]:
y_train

array([5, 0, 4, ..., 5, 6, 8], shape=(60000,), dtype=uint8)

In [10]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Input, Dropout

model = Sequential()
model.add(Input((28, 28)))
model.add(Flatten())
model.add(Dense(128, activation='relu')) 
model.add(Dropout(0.2))
model.add(Dense(10))
 

2026-01-29 00:59:06.140164: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [11]:
nonsense_prediction = model(X_train[:1]).numpy()
nonsense_prediction

array([[ 0.88865083,  0.4711559 , -0.30232424, -0.08134252, -0.42293414,
        -0.01248086,  0.2815886 , -0.10491798, -0.519844  , -0.7098059 ]],
      dtype=float32)

In [12]:
tf.nn.softmax(nonsense_prediction).numpy().sum()

np.float32(1.0)

In [13]:
from tensorflow.keras.losses import SparseCategoricalCrossentropy
loss_fn = SparseCategoricalCrossentropy(from_logits = True)
loss_fn(y_train[:1], nonsense_prediction)

<tf.Tensor: shape=(), dtype=float32, numpy=2.377981662750244>

NOW WE ARE GOING TO COMPILE THE MODEL AND TRAIN IT;
this means that we are going to define an optimizer, specify the loss function, we choose metrics to take a look at, and make the model ready for training.

In [14]:
from tensorflow.keras.optimizers import Adam
optimizer = Adam(learning_rate = 0.01)
model.compile(optimizer=optimizer, loss=loss_fn, metrics=['accuracy'])

In [15]:
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9049 - loss: 0.3177
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9313 - loss: 0.2427
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9357 - loss: 0.2308
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9403 - loss: 0.2187
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9460 - loss: 0.1997
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9467 - loss: 0.2068
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9497 - loss: 0.1940
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9507 - loss: 0.1899
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9521 - loss: 0.1915
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9526 - loss: 0.1888


In [16]:
model.evaluate(X_test, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 683us/step - accuracy: 0.9606 - loss: 0.2046


[0.2046169638633728, 0.9606000185012817]

NOTE THAT : Hyperparameter tuning is done on the third portion of data called the validation dataset for optimal performance

In [17]:
tf.argmax(tf.nn.softmax(model(X_test[:1])).numpy(), axis=1) #Prediction

<tf.Tensor: shape=(1,), dtype=int64, numpy=array([7])>

In [18]:
y_test[:1] # Ground truth

array([7], dtype=uint8)

REGRESSION TASK

In [20]:
 import pandas as pd

 df = pd.read_csv('Data/housing.csv')

In [24]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [26]:
X_train_scaled

array([[ 1.08895015, -1.47678757,  0.22833012, ...,  0.02563244,
         0.78185777, -1.1103204 ],
       [ 0.6430647 , -0.84104667, -0.05906165, ...,  0.06404161,
         0.7443945 , -1.1053308 ],
       [-0.62703004,  1.86085216, -0.67750182, ..., -0.13511797,
         1.0019545 , -1.42965487],
       ...,
       [ 0.4604001 ,  1.22511126,  0.10868589, ..., -0.03849659,
        -0.7635022 ,  0.56119595],
       [-1.11881935,  0.27149991, -0.40854872, ...,  0.05008253,
        -1.32076837,  2.09300348],
       [ 0.53525138,  1.30457887,  0.18270429, ..., -0.03324467,
        -0.84311165,  0.72086319]], shape=(16512, 8))

In [27]:
X_train_scaled.shape

(16512, 8)

In [28]:
model = Sequential()
model.add(Input((8,)))
model.add(Dense(64, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(1))

In [30]:
model.compile(optimizer='adam', loss='mse', metrics=['mae','r2_score'])

In [31]:
model.fit(X_train_scaled, y_train, epochs=10)

Epoch 1/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 798us/step - loss: 0.8455 - mae: 0.6176 - r2_score: 0.3643 
Epoch 2/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - loss: 0.4209 - mae: 0.4556 - r2_score: 0.6836
Epoch 3/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 0s 783us/step - loss: 0.4007 - mae: 0.4346 - r2_score: 0.6987
Epoch 4/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 0s 807us/step - loss: 0.3563 - mae: 0.4191 - r2_score: 0.7321
Epoch 5/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 0s 767us/step - loss: 0.3278 - mae: 0.4043 - r2_score: 0.7535
Epoch 6/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - loss: 0.3325 - mae: 0.3994 - r2_score: 0.7500
Epoch 7/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 0s 806us/step - loss: 0.3188 - mae: 0.3930 - r2_score: 0.7603
Epoch 8/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - loss: 0.3051 - mae: 0.3849 - r2_score: 0.7706
Epoch 9/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - loss: 0.3012 - mae: 0.3808 - r2_score: 0.7735
Epoch 10/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 0s 809us/step - loss: 0.3306 - mae: 0.38

In [32]:
model.evaluate(X_test_scaled, y_test)

129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - loss: 0.3151 - mae: 0.3739 - r2_score: 0.7644


[0.3151496648788452, 0.37394407391548157, 0.7643784284591675]

In [33]:
df.MedHouseVal.describe()

count    20640.000000
mean         2.068558
std          1.153956
min          0.149990
25%          1.196000
50%          1.797000
75%          2.647250
max          5.000010
Name: MedHouseVal, dtype: float64